import React, { useEffect } from "react";
import { Link } from "react-router-dom";

import routes from "../../routes/routes";
import styles from "./secondary.module.scss";

import { useHistory } from "react-router-dom";
import goBack from "../../assets/SkillzImages/goBackBtn.svg";
import Layout from "../../components/Layout";

const Privacy = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  });
  const history = useHistory();
  return (
    <>
      <button className={styles.goBack} onClick={() => history.goBack()}>
        <img src={goBack} alt="go back" />
      </button>
      <div>
        <header className={styles.privacyHeader}>
          <h1>Privacy Policy</h1>
        </header>
        <div className={styles.privacyContent}>
          <Layout>
            <div>
              <p>Last updated: July 23, 2020</p>
              <p>
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
                information when You use the Service and tells You about Your privacy rights and how the law protects
                You.
              </p>
              <p>
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
                collection and use of information in accordance with this Privacy Policy..
              </p>
            </div>
            <div>
              <section>
                <h1>Interpretation and Definitions</h1>
                <h2>Interpretation</h2>
                <p>
                  The words of which the initial letter is capitalized have meanings defined under the following
                  conditions. The following definitions shall have the same meaning regardless of whether they appear in
                  singular or in plural.
                </p>
              </section>
              <section>
                <h2>Definitions</h2>
                <p>For the purposes of this Privacy Policy:</p>
                <ul>
                  <li>
                    <b>You </b>mean the individual accessing or using the Service, or the company, or other legal entity
                    on behalf of which such individual is accessing or using the Service, as applicable.
                  </li>
                  <li>
                    <b>Company </b> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers
                    to uSkillz LLC.
                  </li>
                  <li>
                    <b>Affiliate </b>means an entity that controls, is controlled by or is under common control with a
                    party, where "control" means ownership of 50% or more of the shares, equity interest or other
                    securities entitled to vote for election of directors or other managing authority.
                  </li>
                  <li>
                    <b>Account </b>means a unique account created for You to access our Service or parts of our Service.
                  </li>
                  <li>
                    <b>Website </b> refers to uSkillz, accessible from{" "}
                    <a href="https:// uskillz.io/">https:// uskillz.io/</a>
                  </li>
                  <li>
                    <b>Service </b>refers to the Website.
                  </li>
                  <li>
                    <b>Service Provider </b>means any natural or legal person who processes the data on behalf of the
                    Company. It refers to third-party companies or individuals employed by the Company to facilitate the
                    Service, to provide the Service on behalf of the Company, to perform services related to the Service
                    or to assist the Company in analyzing how the Service is used.
                  </li>
                  <li>
                    <b>Third-party Social Media Service </b>refers to any website or any social network website through
                    which a User can log in or create an account to use the Service.
                  </li>
                  <li>
                    <b>Personal Data </b>is any information that relates to an identified or identifiable individual.
                  </li>
                  <li>
                    <b>Cookies </b>are small files that are placed on Your computer, mobile device or any other device
                    by a website, containing the details of Your browsing history on that website among its many uses
                  </li>
                  <li>
                    <b>Device </b>means any device that can access the Service such as a computer, a cell phone or a
                    digital tablet.
                  </li>
                  <li>
                    <b>Usage Data </b>refers to data collected automatically, either generated by the use of the Service
                    or from the Service infrastructure itself (for example, the duration of a page visit).
                  </li>
                </ul>
              </section>
            </div>
            <div>
              <section>
                <h1>Collecting and Using Your Personal Data</h1>
                <h2>Types of Data Collected</h2>
                <h3>Personal Data</h3>
                <p>
                  While using Our Service, We may ask You to provide Us with certain personally identifiable information
                  that can be used to contact or identify You. Personally identifiable information may include, but is
                  not limited to:
                </p>
                <ul>
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Usage Data</li>
                </ul>
              </section>
              <section>
                <h3>Usage Data</h3>
                <p>Usage Data is collected automatically when using the Service.</p>
                <p>
                  Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address),
                  browser type, browser version, the pages of our Service that You visit, the time and date of Your
                  visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
                <p>
                  When You access the Service by or through a mobile device, We may collect certain information
                  automatically, including, but not limited to, the type of mobile device You use, Your mobile device
                  unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile
                  Internet browser You use, unique device identifiers and other diagnostic data.
                </p>
                <p>
                  We may also collect information that Your browser sends whenever You visit our Service or when You
                  access the Service by or through a mobile device.
                </p>
                <h3>Tracking Technologies and Cookies</h3>
                <p>
                  We use Cookies and similar tracking technologies to track the activity on Our Service and store
                  certain information. Tracking technologies used are beacons, tags, and scripts to collect and track
                  information and to improve and analyze Our Service.
                </p>
                <p>
                  You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.
                  However, if You do not accept Cookies, You may not be able to use some parts of our Service
                </p>
                <p>
                  Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your personal computer
                  or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web
                  browser.
                </p>
                <p>We use both session and persistent Cookies for the purposes set out below:</p>
                <ul>
                  <li>
                    <h4>Necessary / Essential Cookies</h4>
                    <p>Type: Session Cookies</p>
                    <p>Administered by: Us</p>
                    <p>
                      Purpose: These Cookies are essential to provide You with services available through the Website
                      and to enable You to use some of its features. They help to authenticate users and prevent
                      fraudulent use of user accounts. Without these Cookies, the services that You have asked for
                      cannot be provided, and We only use these Cookies to provide You with those services.
                    </p>
                  </li>
                  <li>
                    <h4>Cookies Policy / Notice Acceptance Cookies</h4>
                    <p>Type: Persistent Cookies</p>
                    <p>Administered by: Us</p>
                    <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
                  </li>
                  <li>
                    <h4>Functionality Cookies</h4>
                    <p>Type: Persistent Cookies</p>
                    <p>Administered by: Us</p>
                    <p>
                      Purpose: These Cookies allow us to remember choices You make when You use the Website, such as
                      remembering your login details or language preference. The purpose of these Cookies is to provide
                      You with a more personal experience and to avoid You having to re-enter your preferences every
                      time You use the Website.
                    </p>
                    <p>
                      For more information about the cookies we use and your choices regarding cookies, please visit our
                      Cookies Policy or the Cookies section of our Privacy Policy.
                    </p>
                  </li>
                </ul>
              </section>
              <section>
                <h3>Use of Your Personal Data</h3>
                <p>The Company may use Personal Data for the following purposes:</p>
                <ul>
                  <li>
                    <b>To provide and maintain our Service</b>, including to monitor the usage of our Service.
                  </li>
                  <li>
                    <b>To manage Your Account:</b> to manage Your registration as a user of the Service. The Personal
                    Data You provide can give You access to different functionalities of the Service that are available
                    to You as a registered user.
                  </li>
                  <li>
                    <b>For the performance of a contract:</b> he development, compliance and undertaking of the purchase
                    contract for the products, items or services You have purchased or of any other contract with Us
                    through the Service.
                  </li>
                  <li>
                    <b>To contact You:</b> To contact You by email, telephone calls, SMS, or other equivalent forms of
                    electronic communication, such as a mobile application's push notifications regarding updates or
                    informative communications related to the functionalities, products or contracted services,
                    including the security updates, when necessary or reasonable for their implementation.
                  </li>
                  <li>
                    <b>To provide You</b> with news, special offers and general information about other goods, services
                    and events which we offer that are similar to those that you have already purchased or enquired
                    about unless You have opted not to receive such information.
                  </li>
                  <li>
                    <b>To manage Your requests:</b> To attend and manage Your requests to Us.
                  </li>
                </ul>
                <p>We may share your personal information in the following situations:</p>
                <ul>
                  <li>
                    <b>With Service Providers:</b> We may share Your personal information with Service Providers to
                    monitor and analyze the use of our Service, to contact You.
                  </li>
                  <li>
                    <b>For Business transfers:</b> We may share or transfer Your personal information in connection
                    with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of
                    all or a portion of our business to another company.
                  </li>
                  <li>
                    <b>With Affiliates:</b> We may share Your information with Our affiliates, in which case we will
                    require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any
                    other subsidiaries, joint venture partners or other companies that We control or that are under
                    common control with Us.
                  </li>
                  <li>
                    <b>With Business partners:</b> We may share Your information with Our business partners to offer You
                    certain products, services or promotions.
                  </li>
                  <li>
                    <b>With other users:</b> when You share personal information or otherwise interact in the public
                    areas with other users, such information may be viewed by all users and may be publicly distributed
                    outside. If You interact with other users or register through a Third-Party Social Media Service,
                    Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and
                    description of Your activity. Similarly, other users will be able to view descriptions of Your
                    activity, communicate with You and view Your profile.
                  </li>
                </ul>
                <h3>Retention of Your Personal Data</h3>
                <p>
                  The Company will retain Your Personal Data only for as long as is necessary for the purposes set out
                  in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply
                  with our legal obligations (for example, if we are required to retain your data to comply with
                  applicable laws), resolve disputes, and enforce our legal agreements and policies.
                </p>
                <p>
                  The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally
                  retained for a shorter period of time, except when this data is used to strengthen the security or to
                  improve the functionality of Our Service, or We are legally obligated to retain this data for longer
                  time periods
                </p>
              </section>
              <section>
                <h3>Transfer of Your Personal Data</h3>
                <p>
                  Your information, including Personal Data, is processed at the Company's operating offices and in any
                  other places where the parties involved in the processing are located. It means that this information
                  may be transferred to — and maintained on — computers located outside of Your state, province, country
                  or other governmental jurisdiction where the data protection laws may differ than those from Your
                  jurisdiction.
                </p>
                <p>
                  Your consent to this Privacy Policy followed by Your submission of such information represents Your
                  agreement to that transfer.
                </p>
                <p>
                  The Company will take all steps reasonably necessary to ensure that Your data is treated securely and
                  in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an
                  organization or a country unless there are adequate controls in place including the security of Your
                  data and other personal information.
                </p>
              </section>
              <section>
                <h3>Disclosure of Your Personal Data</h3>
                <h4>Business Transactions</h4>
                <p>
                  If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be
                  transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a
                  different Privacy Policy
                </p>
                <h4>Law enforcement</h4>
                <p>
                  Under certain circumstances, the Company may be required to disclose Your Personal Data if required to
                  do so by law or in response to valid requests by public authorities (e.g. a court or a government
                  agency).
                </p>
                <h4>Other legal requirements</h4>
                <p>
                  The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
                </p>
                <ul>
                  <li>Comply with a legal obligation</li>
                  <li>Protect and defend the rights or property of the Company</li>
                  <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                  <li>Protect the personal safety of Users of the Service or the public</li>
                  <li>Protect against legal liability</li>
                </ul>
              </section>
              <section>
                <h3>Protect against legal liability</h3>
                <p>
                  The security of Your Personal Data is important to Us, but remember that no method of transmission
                  over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially
                  acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                </p>
              </section>
            </div>
            <div>
              <h2>Contact Us</h2>
              If you have any questions about this Privacy Policy, You can contact us:
              <ul>
                <li>By email: uskillz.io@gmail.com</li>
              </ul>
            </div>
          </Layout>
        </div>
      </div>
    </>
  );
};

export default Privacy;
