//абота с авторизацией

export const USER_DATA_LOADING = "USER_DATA_LOADING";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_FAILED = "USER_DATA_FAILED";

export const PASSWORD_RESET_LOADING = "PASSWORD_RESET_LOADING";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED";

export const PASSWORD_RESET_CONFIRM_LOADING = "PASSWORD_RESET_CONFIRM_LOADING";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAILED = "PASSWORD_RESET_CONFIRM_FAILED";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const SIGN_OUT = "SIGN_OUT";

//работа с формой
export const CHANGE_FIELDS = "CHANGE_FIELDS";

//Прогресс бар и заполнение инфы

export const SET_NEXT_STEP = "SET_NEXT_STEP";

export const GET_UNIVERSITY_LIST = "GET_UNIVERSITY_LIST";
export const GET_DEGREE_LIST = "GET_DEGREE_LIST";
export const GET_PILOT_LIST = "GET_PILOT_LIST";

// работа с профилем
export const UPDATE_PROFILE_LOADING = "UPDATE_PROFILE_LOADING";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";

export const CHANGE_PASS_LOADING = "CHANGE_PASS_LOADING";
export const CHANGE_PASS_SUCCESS = "CHANGE_PASS_SUCCESS";
export const CHANGE_PASS_FAILED = "CHANGE_PASS_FAILED";

//работа со скиллами

export const GET_SOFT_SKILLS = "GET_SOFT_SKILLS";
export const GET_SOFT_SKILLS_HAVE = "GET_SOFT_SKILLS_HAVE";
export const GET_SOFT_SKILLS_NEED = "GET_SOFT_SKILLS_NEED";

export const GET_HARD_SKILLS = "GET_HARD_SKILLS";
export const GET_HARD_SKILLS_HAVE = "GET_HARD_SKILLS_HAVE";
export const GET_HARD_SKILLS_NEED = "GET_HARD_SKILLS_NEED";

export const ADD_SOFT_SKILLS_LOADING = "ADD_SOFT_SKILLS_LOADING";
export const ADD_SOFT_SKILLS_SUCCESS = "ADD_SOFT_SKILLS_SUCCESS";
export const ADD_SOFT_SKILLS_FAILED = "ADD_SOFT_SKILLS_FAILED";

export const ADD_HARD_SKILLS_LOADING = "ADD_HARD_SKILLS_LOADING";
export const ADD_HARD_SKILLS_SUCCESS = "ADD_HARD_SKILLS_SUCCESS";
export const ADD_HARD_SKILLS_FAILED = "ADD_HARD_SKILLS_FAILED";

export const DELETE_SKILL_LOADING = "DELETE_SKILL_LOADING";
export const DELETE_SKILL_SUCCESS = "DELETE_SKILL_SUCCESS";
export const DELETE_SKILL_FAILED = "DELETE_SKILL_FAILED";

export const GET_COMPANY_LIST = "GET_COMPANY_LIST";
export const GET_INDUSTRY_LIST = "GET_INDUSTRY_LIST ";
export const GET_EXP_LIST = "GET_EXP_LIST";

export const ADD_COMPANY_LOADING = "ADD_COMPANY_LOADING";
export const ADD_COMPANY_SUCCESS = "ADD_COMPANY_SUCCESS";
export const ADD_COMPANY_FAILED = "ADD_COMPANY_FAILED";

export const ADD_INDUSTRY_LOADING = "ADD_INDUSTRY_LOADING";
export const ADD_INDUSTRY_SUCCESS = "ADD_INDUSTRY_SUCCESS";
export const ADD_INDUSTRY_FAILED = "ADD_INDUSTRY_FAILED";

export const CREATE_EXP_LOADING = "CREATE_EXP_LOADING";
export const CREATE_EXP_SUCCESS = "CREATE_EXP_SUCCESS";
export const CREATE_EXP_FAILED = "CREATE_EXP_FAILED";

export const EDIT_EXP_LOADING = "EDIT_EXP_LOADING";
export const EDIT_EXP_SUCCESS = "EDIT_EXP_SUCCESS";
export const EDIT_EXP_FAILED = "EDIT_EXP_FAILED";

/// работа с CV

export const GET_COMPANY_IN_INDUSTRY = "GET_COMPANY_IN_INDUSTRY";
export const GET_EXP_TYPE_LIST = "GET_EXP_TYPE_LIST";
export const SET_CURRENT_EXP_DETAIL = "SET_CURRENT_EXP_DETAIL";

/// очистка состояний
export const DEFAULT_PROCESS_FETCH = "DEFAULT_PROCESS_FETCH";
export const CLEAR_FIELDS = "CLEAR_FIELDS";

/// Dashboard types

export const SWITCH_TO_ADMIN = "SWITCH_TO_ADMIN";
export const GET_TEAMS_LIST = "GET_TEAMS_LIST";
export const GET_MEMBERS_LIST = "GET_MEMBERS_LIST";
export const GET_SKILLS_TEAMS_LIST = "GET_SKILLS_TEAMS_LIST";
export const GET_EXP_AND_INDUSTRIES_LIST = "GET_EXP_AND_INDUSTRIES_LIST";
export const GET_GRAPHS_SKILLS_LIST = "GET_GRAPHS_SKILLS_LIST";
export const GET_GRAPHS_SKILLS_NEED_LIST = "GET_GRAPHS_SKILLS_NEED_LIST";
export const GET_EXP_AND_INDUSTRIES_GRAPHS_LIST = "GET_EXP_AND_INDUSTRIES_GRAPHS_LIST";

export const CREATE_TEAM_LOADING = "CREATE_TEAM_LOADING";
export const CREATE_TEAM_SUCCESS = "CREATE_TEAM_SUCCESS";
export const CREATE_TEAM_FAILED = "CREATE_TEAM_FAILED";

export const DELETE_TEAM_LOADING = "DELETE_TEAM_LOADING";
export const DELETE_TEAM_SUCCESS = "DELETE_TEAM_SUCCESS";
export const DELETE_TEAM_FAILED = "DELETE_TEAM_FAILED";
